# Generated by Django 4.2 on 2024-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('parent', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('menu_name', models.CharField(max_length=80))
            ],
        ),
    ]
